version: '3'

services:
    prometheus:
        image: prom/prometheus 
        ports:
            - 9090:9090
        volumes:
            - ./prometheus:/etc/prometheus/
        networks:
            - docker
    grafana:
        image: grafana/grafana-enterprise
        ports:
            - 3000:3000
        volumes:
            - ./grafana/datasources:/etc/grafana/provisioning/datasources
            - ./grafana/providers:/etc/grafana/provisioning/dashboards
            - ./grafana/dashboards:/var/lib/grafana/dashboards
        networks:
            - docker
networks:
    docker:
        driver: bridge
        ipam:
            driver: default
            config:
              - subnet: "172.31.0.1/16"
