---
- name: Setting up Prometheus Node Exporter, Prometheus and Grafana for DevOps monitoring
  hosts: all
  vars:
    - node_exporter_version: 1.3.1
    - platform: amd64

  tasks:
  
  - name: Install necessary packages
    become: yes
    apt:
        pkg:
        - docker
        - docker-compose
        update_cache: yes

  - name: Download Prometheus Node Exporter package
    get_url:
        url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-{{ platform }}.tar.gz"
        dest: "./node_exporter-{{ node_exporter_version }}.linux-{{ platform }}.tar.gz"

  - name: Unarchive downloaded Prometheus Node Exporter package
    unarchive:
        src: "./node_exporter-{{ node_exporter_version }}.linux-{{ platform }}.tar.gz"
        dest: .
        remote_src: yes

  - name: Create node_exporter user
    user:
        name: node_exporter
        shell: /sbin/nologin
    become: yes

  - name: Change ownership of Prometheus Node Exporter executable binary
    file:
        path: "./node_exporter-{{ node_exporter_version }}.linux-{{ platform }}/node_exporter"
        owner: node_exporter
        group: node_exporter
    become: yes

  - name: Create /var/log/node_exporter directory for Prometheus Node Exporter logs
    file:
        path: /var/log/node_exporter
        state: directory
        owner: node_exporter
        group: node_exporter
    become: yes

  - name: Move Prometheus Node Exporter executable binary to /usr/sbin directory
    command: 
        cmd: mv "./node_exporter-{{ node_exporter_version }}.linux-{{ platform }}/node_exporter" /usr/sbin/
        creates: /usr/sbin/node_exporter
    become: yes

  - name: Copy Prometheus Node Exporter systemd unit file
    copy:
        src: node_exporter.service
        dest: /etc/systemd/system/node_exporter.service
    become: yes

  - name: Delete unnecessary Prometheus Node Exporter files
    file:
        path: "{{ item }}"
        state: absent
    loop:
        - node_exporter-{{ node_exporter_version }}.linux-{{ platform }}.tar.gz
        - node_exporter-{{ node_exporter_version }}.linux-{{ platform }}/

  - name: Start and enable Prometheus Node Exporter service
    systemd:
        daemon_reload: yes
        name: node_exporter.service
        state: started
        enabled: yes
    become: yes

  - name: Create directories for storing configuration files of Prometheus and Grafana
    file:
        path: "./{{ item }}"
        state: directory
    loop:
        - prometheus
        - grafana
        - grafana/datasources
        - grafana/providers
        - grafana/dashboards

  - name: Upload necessary configuration files of Prometheus and Grafana
    copy:
        src: "{{ item.directory }}/{{ item.filename }}"
        dest: "{{ item.directory }}"
    loop:
        - { directory: ., filename: docker-compose.yml }
        - { directory: prometheus, filename: prometheus.yml }
        - { directory: grafana/datasources, filename: node-exporter.yml }
        - { directory: grafana/providers, filename: node-exporter.yml }
        - { directory: grafana/dashboards, filename: node-exporter-full.json }

  - name: Run Docker Compose
    docker_compose:
        project_src: .
    become: yes

  - name: Pause for correct visualization of metrics from Prometheus Node Exporter on the Grafana dashboard
    pause:
        minutes: 4
